version: '3.1'

services:
  db:
    image: postgres
    restart: always
    container_name: db
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: practice
  server:
    build: .
    command: java -jar app.jar
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/practice
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
    - 80:80
    depends_on:
      - db